universe = vanilla
executable = exec.sh
transfer_input_files = condor_torch.py
output = log_gpu.out
error = log_gpu.err
Requirements = ( BOSCOCluster =!= "t3serv008.mit.edu" && BOSCOCluster =!= "ce03.cmsaf.mit.edu" && BOSCOCluster =!= "eofe8.mit.edu")
log = log_gpu.log
use_x509userproxy = True
+AccountingGroup = "analysis.<username>"
ShouldTransferFiles = YES
RequestGPUs=1
+DESIRED_Sites = "mit_tier2"
#For tier3
#+DESIRED_Sites = "mit_tier3"
when_to_transfer_output = ON_EXIT
queue
