#!/usr/bin/env python
import os,sys

min = int(sys.argv[1])
max = int(sys.argv[2])

os.system("cat base_sub > submit")

with open("submit","a") as fH:
    for i in range(min,max+1,1):
        id = str(i)
        fH.write("Arguments             = %d\n"%(i)) 
        fH.write("Transfer_output_files = debug_%s.result\n"%(id))
        fH.write("Output                = debug_%s.out\n"%(id))
        fH.write("Error                 = debug_%s.err\n"%(id))
        fH.write("Queue\n")
