#!/usr/bin/env python
#
import os,sys

min = int(sys.argv[1])
max = int(sys.argv[2])

os.system("cat base_sub > submit")

with open("submit","a") as fH:
    for i in range(min,max+1,1):
        id = str(i)
        #fH.write("transfer_output_files = test-all_%s.result\n"%(id))
        fH.write("Output                = test-all_%s.out\n"%(id))
        fH.write("Error                 = test-all_%s.err\n"%(id))
        fH.write("Queue\n")
