#!/bin/bash
#---------------------------------------------------------------------------------------------------
#
# Script to run a simple test checking which flags are available of the given CPUs on the
# workernode.
#
#---------------------------------------------------------------------------------------------------

# show the arguments
echo ""; echo " ## Arguments"
echo $@


# make sure the PATH is properly set
export PATH="/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

# show the directory
echo ""; echo " ## Directory"
pwd
echo ""
ls -lhrt


# show cvmfs
echo ""; echo " ## List root (/)"
ls -l /
echo ""; echo " ## Load CMS default setup"
ls -lhrt /cvmfs/cms.cern.ch/cmsset_default.sh
source   /cvmfs/cms.cern.ch/cmsset_default.sh

# show singularity
echo ""; echo " ## Singularity"
which singularity
if [ ".$?" == "0" ]
then
  singularity --version
else
  echo " ERROR - singularity not found"
fi

# now let's do what we came for
echo ""; echo " ## Flags: cat /proc/cpuinfo | grep flags | sort -u"
flags=`cat /proc/cpuinfo | grep flags | sort -u`
host=`hostname`
echo " $host: $flags"

# show my running environment
echo ""; echo " ## Environment"
env

# now sleep to make those queue busy
echo ""; echo " ## Sleep 20"
sleep 20
