#!/bin/bash
##
##SBATCH --job-name=test
##SBATCH --output=res_%j.txt
##SBATCH --error=err_%j.txt
##
##SBATCH --time=10:00
##SBATCH --mem-per-cpu=100
#

matlab -nodisplay -nodesktop -r "run matlab_example.m"
